version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    groups:
      github_actions_all:
        patterns:
          - "*"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "libp2p"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "embedded-hal"
      - dependency-name: "tower-http"
      - dependency-name: "sha2"
        update-types: ["version-update:semver-major"]
      - dependency-name: "bincode"
        update-types: ["version-update:semver-major"]
      - dependency-name: "uniffi"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "linux-embedded-hal"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "keyring"
        update-types: ["version-update:semver-major"]
      - dependency-name: "rand"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tower"
        update-types: ["version-update:semver-major"]
