// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.mycelium

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.INSTANCE.ffi_mycelium_ffi_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_mycelium_ffi_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 *
 * @suppress
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setLong(0, value.capacity)
        pointer.setLong(8, value.len)
        pointer.setPointer(16, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getLong(0))
        value.writeField("len", pointer.getLong(8))
        value.writeField("data", pointer.getLong(16))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    private val counter = java.util.concurrent.atomic.AtomicLong(0)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(1)
        map.put(handle, obj)
        return handle
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "uniffi_mycelium"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFuture(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureFree? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureFree? = null,
    ): UniffiForeignFuture(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFuture) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructPointer(
    @JvmField internal var `returnValue`: Pointer = Pointer.NULL,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Pointer = Pointer.NULL,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructPointer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructPointer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompletePointer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructPointer.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureStructVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructVoid.UniffiByValue,)
}
internal interface UniffiCallbackInterfaceNodeEventCallbackMethod0 : com.sun.jna.Callback {
    fun callback(`uniffiHandle`: Long,`peerId`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,)
}
internal interface UniffiCallbackInterfaceNodeEventCallbackMethod1 : com.sun.jna.Callback {
    fun callback(`uniffiHandle`: Long,`peerId`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,)
}
internal interface UniffiCallbackInterfaceNodeEventCallbackMethod2 : com.sun.jna.Callback {
    fun callback(`uniffiHandle`: Long,`message`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,)
}
internal interface UniffiCallbackInterfaceNodeEventCallbackMethod3 : com.sun.jna.Callback {
    fun callback(`uniffiHandle`: Long,`message`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,)
}
internal interface UniffiCallbackInterfaceNodeEventCallbackMethod4 : com.sun.jna.Callback {
    fun callback(`uniffiHandle`: Long,`post`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,)
}
internal interface UniffiCallbackInterfaceNodeEventCallbackMethod5 : com.sun.jna.Callback {
    fun callback(`uniffiHandle`: Long,`mode`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,)
}
@Structure.FieldOrder("onPeerDiscovered", "onPeerLost", "onChatReceived", "onMailReceived", "onBulletinReceived", "onConnectivityChanged", "uniffiFree")
internal open class UniffiVTableCallbackInterfaceNodeEventCallback(
    @JvmField internal var `onPeerDiscovered`: UniffiCallbackInterfaceNodeEventCallbackMethod0? = null,
    @JvmField internal var `onPeerLost`: UniffiCallbackInterfaceNodeEventCallbackMethod1? = null,
    @JvmField internal var `onChatReceived`: UniffiCallbackInterfaceNodeEventCallbackMethod2? = null,
    @JvmField internal var `onMailReceived`: UniffiCallbackInterfaceNodeEventCallbackMethod3? = null,
    @JvmField internal var `onBulletinReceived`: UniffiCallbackInterfaceNodeEventCallbackMethod4? = null,
    @JvmField internal var `onConnectivityChanged`: UniffiCallbackInterfaceNodeEventCallbackMethod5? = null,
    @JvmField internal var `uniffiFree`: UniffiCallbackInterfaceFree? = null,
) : Structure() {
    class UniffiByValue(
        `onPeerDiscovered`: UniffiCallbackInterfaceNodeEventCallbackMethod0? = null,
        `onPeerLost`: UniffiCallbackInterfaceNodeEventCallbackMethod1? = null,
        `onChatReceived`: UniffiCallbackInterfaceNodeEventCallbackMethod2? = null,
        `onMailReceived`: UniffiCallbackInterfaceNodeEventCallbackMethod3? = null,
        `onBulletinReceived`: UniffiCallbackInterfaceNodeEventCallbackMethod4? = null,
        `onConnectivityChanged`: UniffiCallbackInterfaceNodeEventCallbackMethod5? = null,
        `uniffiFree`: UniffiCallbackInterfaceFree? = null,
    ): UniffiVTableCallbackInterfaceNodeEventCallback(`onPeerDiscovered`,`onPeerLost`,`onChatReceived`,`onMailReceived`,`onBulletinReceived`,`onConnectivityChanged`,`uniffiFree`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiVTableCallbackInterfaceNodeEventCallback) {
        `onPeerDiscovered` = other.`onPeerDiscovered`
        `onPeerLost` = other.`onPeerLost`
        `onChatReceived` = other.`onChatReceived`
        `onMailReceived` = other.`onMailReceived`
        `onBulletinReceived` = other.`onBulletinReceived`
        `onConnectivityChanged` = other.`onConnectivityChanged`
        `uniffiFree` = other.`uniffiFree`
    }

}































































































































// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

internal interface UniffiLib : Library {
    companion object {
        internal val INSTANCE: UniffiLib by lazy {
            loadIndirect<UniffiLib>(componentName = "mycelium")
            .also { lib: UniffiLib ->
                uniffiCheckContractApiVersion(lib)
                uniffiCheckApiChecksums(lib)
                uniffiCallbackInterfaceNodeEventCallback.register(lib)
                }
        }
        
    }

    fun uniffi_mycelium_ffi_fn_init_callback_vtable_nodeeventcallback(`vtable`: UniffiVTableCallbackInterfaceNodeEventCallback,
    ): Unit
    fun uniffi_mycelium_ffi_fn_func_add_bootstrap_peer(`multiaddr`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_mycelium_ffi_fn_func_build_payment_request_uri(`toAddress`: RustBuffer.ByValue,`amountMuon`: Long,`memo`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_mycelium_ffi_fn_func_bulletins_for_scope(`scope`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_mycelium_ffi_fn_func_chat_history(`peerId`: RustBuffer.ByValue,`limit`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_mycelium_ffi_fn_func_current_connectivity_mode(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_mycelium_ffi_fn_func_display_name(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_mycelium_ffi_fn_func_get_hot_wallet_config(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_mycelium_ffi_fn_func_hot_wallet_status(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_mycelium_ffi_fn_func_init_node(`config`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_mycelium_ffi_fn_func_known_peers(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_mycelium_ffi_fn_func_local_peer_id(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_mycelium_ffi_fn_func_mail_inbox(`limit`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_mycelium_ffi_fn_func_mail_sent(`limit`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_mycelium_ffi_fn_func_mark_mail_read(`mailId`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_mycelium_ffi_fn_func_metrics(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_mycelium_ffi_fn_func_parse_payment_request_uri(`uri`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_mycelium_ffi_fn_func_post_bulletin(`scope`: RustBuffer.ByValue,`title`: RustBuffer.ByValue,`body`: RustBuffer.ByValue,`ttlSecs`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_mycelium_ffi_fn_func_request_faucet(uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_mycelium_ffi_fn_func_send_chat_broadcast(`body`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_mycelium_ffi_fn_func_send_chat_direct(`toPeer`: RustBuffer.ByValue,`body`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_mycelium_ffi_fn_func_send_mail(`toPeer`: RustBuffer.ByValue,`subject`: RustBuffer.ByValue,`body`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_mycelium_ffi_fn_func_send_transaction(`toAddress`: RustBuffer.ByValue,`amountMuon`: Long,`memo`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_mycelium_ffi_fn_func_set_cold_wallet_address(`address`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_mycelium_ffi_fn_func_set_display_name(`name`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_mycelium_ffi_fn_func_set_energy_state(`state`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_mycelium_ffi_fn_func_set_event_callback(`callback`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_mycelium_ffi_fn_func_set_hot_wallet_config(`config`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_mycelium_ffi_fn_func_stop_node(uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_mycelium_ffi_fn_func_wallet_address(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_mycelium_ffi_fn_func_wallet_balance(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_mycelium_ffi_fn_func_wallet_recent_transactions(`limit`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_mycelium_ffi_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_mycelium_ffi_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_mycelium_ffi_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun ffi_mycelium_ffi_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_mycelium_ffi_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_free_u8(`handle`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_mycelium_ffi_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_free_i8(`handle`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_mycelium_ffi_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_free_u16(`handle`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_mycelium_ffi_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_free_i16(`handle`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_mycelium_ffi_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_free_u32(`handle`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_mycelium_ffi_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_free_i32(`handle`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_mycelium_ffi_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_free_u64(`handle`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_mycelium_ffi_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_free_i64(`handle`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_mycelium_ffi_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_free_f32(`handle`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    fun ffi_mycelium_ffi_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_free_f64(`handle`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    fun ffi_mycelium_ffi_rust_future_poll_pointer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_cancel_pointer(`handle`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_free_pointer(`handle`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_complete_pointer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun ffi_mycelium_ffi_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_mycelium_ffi_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_cancel_void(`handle`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_free_void(`handle`: Long,
    ): Unit
    fun ffi_mycelium_ffi_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_mycelium_ffi_checksum_func_add_bootstrap_peer(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_build_payment_request_uri(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_bulletins_for_scope(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_chat_history(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_current_connectivity_mode(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_display_name(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_get_hot_wallet_config(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_hot_wallet_status(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_init_node(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_known_peers(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_local_peer_id(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_mail_inbox(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_mail_sent(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_mark_mail_read(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_metrics(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_parse_payment_request_uri(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_post_bulletin(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_request_faucet(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_send_chat_broadcast(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_send_chat_direct(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_send_mail(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_send_transaction(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_set_cold_wallet_address(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_set_display_name(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_set_energy_state(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_set_event_callback(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_set_hot_wallet_config(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_stop_node(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_wallet_address(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_wallet_balance(
    ): Short
    fun uniffi_mycelium_ffi_checksum_func_wallet_recent_transactions(
    ): Short
    fun uniffi_mycelium_ffi_checksum_method_nodeeventcallback_on_peer_discovered(
    ): Short
    fun uniffi_mycelium_ffi_checksum_method_nodeeventcallback_on_peer_lost(
    ): Short
    fun uniffi_mycelium_ffi_checksum_method_nodeeventcallback_on_chat_received(
    ): Short
    fun uniffi_mycelium_ffi_checksum_method_nodeeventcallback_on_mail_received(
    ): Short
    fun uniffi_mycelium_ffi_checksum_method_nodeeventcallback_on_bulletin_received(
    ): Short
    fun uniffi_mycelium_ffi_checksum_method_nodeeventcallback_on_connectivity_changed(
    ): Short
    fun ffi_mycelium_ffi_uniffi_contract_version(
    ): Int
    
}

private fun uniffiCheckContractApiVersion(lib: UniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_mycelium_ffi_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}

@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: UniffiLib) {
    if (lib.uniffi_mycelium_ffi_checksum_func_add_bootstrap_peer() != 59246.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_build_payment_request_uri() != 16827.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_bulletins_for_scope() != 4068.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_chat_history() != 35631.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_current_connectivity_mode() != 22061.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_display_name() != 36992.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_get_hot_wallet_config() != 28880.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_hot_wallet_status() != 20097.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_init_node() != 22974.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_known_peers() != 29951.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_local_peer_id() != 52468.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_mail_inbox() != 53596.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_mail_sent() != 38151.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_mark_mail_read() != 50661.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_metrics() != 29003.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_parse_payment_request_uri() != 55057.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_post_bulletin() != 6189.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_request_faucet() != 55185.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_send_chat_broadcast() != 26485.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_send_chat_direct() != 57327.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_send_mail() != 35213.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_send_transaction() != 59650.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_set_cold_wallet_address() != 64181.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_set_display_name() != 33565.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_set_energy_state() != 18913.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_set_event_callback() != 51877.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_set_hot_wallet_config() != 32316.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_stop_node() != 29797.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_wallet_address() != 15773.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_wallet_balance() != 49625.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_func_wallet_recent_transactions() != 17514.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_method_nodeeventcallback_on_peer_discovered() != 4491.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_method_nodeeventcallback_on_peer_lost() != 63082.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_method_nodeeventcallback_on_chat_received() != 13871.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_method_nodeeventcallback_on_mail_received() != 11056.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_method_nodeeventcallback_on_bulletin_received() != 53694.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_mycelium_ffi_checksum_method_nodeeventcallback_on_connectivity_changed() != 16580.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            args.filterIsInstance<Disposable>()
                .forEach(Disposable::destroy)
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoPointer

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8UL

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}



data class BulletinPost (
    var `id`: kotlin.String, 
    var `fromDisplayName`: kotlin.String, 
    var `title`: kotlin.String, 
    var `body`: kotlin.String, 
    var `scope`: kotlin.String, 
    var `timestampMs`: kotlin.ULong, 
    var `expiresAtMs`: kotlin.ULong
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeBulletinPost: FfiConverterRustBuffer<BulletinPost> {
    override fun read(buf: ByteBuffer): BulletinPost {
        return BulletinPost(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: BulletinPost) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`fromDisplayName`) +
            FfiConverterString.allocationSize(value.`title`) +
            FfiConverterString.allocationSize(value.`body`) +
            FfiConverterString.allocationSize(value.`scope`) +
            FfiConverterULong.allocationSize(value.`timestampMs`) +
            FfiConverterULong.allocationSize(value.`expiresAtMs`)
    )

    override fun write(value: BulletinPost, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`fromDisplayName`, buf)
            FfiConverterString.write(value.`title`, buf)
            FfiConverterString.write(value.`body`, buf)
            FfiConverterString.write(value.`scope`, buf)
            FfiConverterULong.write(value.`timestampMs`, buf)
            FfiConverterULong.write(value.`expiresAtMs`, buf)
    }
}



data class ChatMessage (
    var `id`: kotlin.String, 
    var `fromPeer`: kotlin.String, 
    var `fromDisplayName`: kotlin.String, 
    var `body`: kotlin.String, 
    var `timestampMs`: kotlin.ULong
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeChatMessage: FfiConverterRustBuffer<ChatMessage> {
    override fun read(buf: ByteBuffer): ChatMessage {
        return ChatMessage(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: ChatMessage) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`fromPeer`) +
            FfiConverterString.allocationSize(value.`fromDisplayName`) +
            FfiConverterString.allocationSize(value.`body`) +
            FfiConverterULong.allocationSize(value.`timestampMs`)
    )

    override fun write(value: ChatMessage, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`fromPeer`, buf)
            FfiConverterString.write(value.`fromDisplayName`, buf)
            FfiConverterString.write(value.`body`, buf)
            FfiConverterULong.write(value.`timestampMs`, buf)
    }
}



data class HotWalletConfig (
    var `maxCacheMuon`: kotlin.ULong, 
    var `refillThresholdMuon`: kotlin.ULong, 
    var `refillAmountMuon`: kotlin.ULong, 
    var `coldWalletAddress`: kotlin.String?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeHotWalletConfig: FfiConverterRustBuffer<HotWalletConfig> {
    override fun read(buf: ByteBuffer): HotWalletConfig {
        return HotWalletConfig(
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: HotWalletConfig) = (
            FfiConverterULong.allocationSize(value.`maxCacheMuon`) +
            FfiConverterULong.allocationSize(value.`refillThresholdMuon`) +
            FfiConverterULong.allocationSize(value.`refillAmountMuon`) +
            FfiConverterOptionalString.allocationSize(value.`coldWalletAddress`)
    )

    override fun write(value: HotWalletConfig, buf: ByteBuffer) {
            FfiConverterULong.write(value.`maxCacheMuon`, buf)
            FfiConverterULong.write(value.`refillThresholdMuon`, buf)
            FfiConverterULong.write(value.`refillAmountMuon`, buf)
            FfiConverterOptionalString.write(value.`coldWalletAddress`, buf)
    }
}



data class HotWalletStatus (
    var `confirmedMuon`: kotlin.ULong, 
    var `pendingMuon`: kotlin.ULong, 
    var `maxCacheMuon`: kotlin.ULong, 
    var `autoRefillEnabled`: kotlin.Boolean, 
    var `needsRefill`: kotlin.Boolean, 
    var `connectivity`: ConnectivityMode
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeHotWalletStatus: FfiConverterRustBuffer<HotWalletStatus> {
    override fun read(buf: ByteBuffer): HotWalletStatus {
        return HotWalletStatus(
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterTypeConnectivityMode.read(buf),
        )
    }

    override fun allocationSize(value: HotWalletStatus) = (
            FfiConverterULong.allocationSize(value.`confirmedMuon`) +
            FfiConverterULong.allocationSize(value.`pendingMuon`) +
            FfiConverterULong.allocationSize(value.`maxCacheMuon`) +
            FfiConverterBoolean.allocationSize(value.`autoRefillEnabled`) +
            FfiConverterBoolean.allocationSize(value.`needsRefill`) +
            FfiConverterTypeConnectivityMode.allocationSize(value.`connectivity`)
    )

    override fun write(value: HotWalletStatus, buf: ByteBuffer) {
            FfiConverterULong.write(value.`confirmedMuon`, buf)
            FfiConverterULong.write(value.`pendingMuon`, buf)
            FfiConverterULong.write(value.`maxCacheMuon`, buf)
            FfiConverterBoolean.write(value.`autoRefillEnabled`, buf)
            FfiConverterBoolean.write(value.`needsRefill`, buf)
            FfiConverterTypeConnectivityMode.write(value.`connectivity`, buf)
    }
}



data class MailMessage (
    var `id`: kotlin.String, 
    var `fromPeer`: kotlin.String, 
    var `fromDisplayName`: kotlin.String, 
    var `toPeer`: kotlin.String, 
    var `subject`: kotlin.String, 
    var `body`: kotlin.String, 
    var `timestampMs`: kotlin.ULong, 
    var `isRead`: kotlin.Boolean
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeMailMessage: FfiConverterRustBuffer<MailMessage> {
    override fun read(buf: ByteBuffer): MailMessage {
        return MailMessage(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterBoolean.read(buf),
        )
    }

    override fun allocationSize(value: MailMessage) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`fromPeer`) +
            FfiConverterString.allocationSize(value.`fromDisplayName`) +
            FfiConverterString.allocationSize(value.`toPeer`) +
            FfiConverterString.allocationSize(value.`subject`) +
            FfiConverterString.allocationSize(value.`body`) +
            FfiConverterULong.allocationSize(value.`timestampMs`) +
            FfiConverterBoolean.allocationSize(value.`isRead`)
    )

    override fun write(value: MailMessage, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`fromPeer`, buf)
            FfiConverterString.write(value.`fromDisplayName`, buf)
            FfiConverterString.write(value.`toPeer`, buf)
            FfiConverterString.write(value.`subject`, buf)
            FfiConverterString.write(value.`body`, buf)
            FfiConverterULong.write(value.`timestampMs`, buf)
            FfiConverterBoolean.write(value.`isRead`, buf)
    }
}



data class NodeConfig (
    var `dbPath`: kotlin.String, 
    var `listenAddr`: kotlin.String, 
    var `displayName`: kotlin.String, 
    var `bootstrapPeers`: List<kotlin.String>
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeNodeConfig: FfiConverterRustBuffer<NodeConfig> {
    override fun read(buf: ByteBuffer): NodeConfig {
        return NodeConfig(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterSequenceString.read(buf),
        )
    }

    override fun allocationSize(value: NodeConfig) = (
            FfiConverterString.allocationSize(value.`dbPath`) +
            FfiConverterString.allocationSize(value.`listenAddr`) +
            FfiConverterString.allocationSize(value.`displayName`) +
            FfiConverterSequenceString.allocationSize(value.`bootstrapPeers`)
    )

    override fun write(value: NodeConfig, buf: ByteBuffer) {
            FfiConverterString.write(value.`dbPath`, buf)
            FfiConverterString.write(value.`listenAddr`, buf)
            FfiConverterString.write(value.`displayName`, buf)
            FfiConverterSequenceString.write(value.`bootstrapPeers`, buf)
    }
}



data class NodeMetrics (
    var `messagesForwarded`: kotlin.ULong, 
    var `messagesDroppedTtl`: kotlin.ULong, 
    var `messagesDroppedQueue`: kotlin.ULong, 
    var `messagesDeliveredLocal`: kotlin.ULong, 
    var `pendingQueueSize`: kotlin.ULong, 
    var `seenCacheSize`: kotlin.ULong
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeNodeMetrics: FfiConverterRustBuffer<NodeMetrics> {
    override fun read(buf: ByteBuffer): NodeMetrics {
        return NodeMetrics(
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: NodeMetrics) = (
            FfiConverterULong.allocationSize(value.`messagesForwarded`) +
            FfiConverterULong.allocationSize(value.`messagesDroppedTtl`) +
            FfiConverterULong.allocationSize(value.`messagesDroppedQueue`) +
            FfiConverterULong.allocationSize(value.`messagesDeliveredLocal`) +
            FfiConverterULong.allocationSize(value.`pendingQueueSize`) +
            FfiConverterULong.allocationSize(value.`seenCacheSize`)
    )

    override fun write(value: NodeMetrics, buf: ByteBuffer) {
            FfiConverterULong.write(value.`messagesForwarded`, buf)
            FfiConverterULong.write(value.`messagesDroppedTtl`, buf)
            FfiConverterULong.write(value.`messagesDroppedQueue`, buf)
            FfiConverterULong.write(value.`messagesDeliveredLocal`, buf)
            FfiConverterULong.write(value.`pendingQueueSize`, buf)
            FfiConverterULong.write(value.`seenCacheSize`, buf)
    }
}



data class PaymentRequestData (
    var `toAddress`: kotlin.String, 
    var `amountMuon`: kotlin.ULong, 
    var `memo`: kotlin.String?, 
    var `expiresAtMs`: kotlin.ULong?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypePaymentRequestData: FfiConverterRustBuffer<PaymentRequestData> {
    override fun read(buf: ByteBuffer): PaymentRequestData {
        return PaymentRequestData(
            FfiConverterString.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalULong.read(buf),
        )
    }

    override fun allocationSize(value: PaymentRequestData) = (
            FfiConverterString.allocationSize(value.`toAddress`) +
            FfiConverterULong.allocationSize(value.`amountMuon`) +
            FfiConverterOptionalString.allocationSize(value.`memo`) +
            FfiConverterOptionalULong.allocationSize(value.`expiresAtMs`)
    )

    override fun write(value: PaymentRequestData, buf: ByteBuffer) {
            FfiConverterString.write(value.`toAddress`, buf)
            FfiConverterULong.write(value.`amountMuon`, buf)
            FfiConverterOptionalString.write(value.`memo`, buf)
            FfiConverterOptionalULong.write(value.`expiresAtMs`, buf)
    }
}



data class TxInfo (
    var `id`: kotlin.String, 
    var `fromAddress`: kotlin.String, 
    var `toAddress`: kotlin.String, 
    var `amountMuon`: kotlin.ULong, 
    var `feeMuon`: kotlin.ULong, 
    var `timestampMs`: kotlin.ULong, 
    var `memo`: kotlin.String?, 
    var `witnessCount`: kotlin.UInt, 
    var `confirmed`: kotlin.Boolean
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeTxInfo: FfiConverterRustBuffer<TxInfo> {
    override fun read(buf: ByteBuffer): TxInfo {
        return TxInfo(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterBoolean.read(buf),
        )
    }

    override fun allocationSize(value: TxInfo) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`fromAddress`) +
            FfiConverterString.allocationSize(value.`toAddress`) +
            FfiConverterULong.allocationSize(value.`amountMuon`) +
            FfiConverterULong.allocationSize(value.`feeMuon`) +
            FfiConverterULong.allocationSize(value.`timestampMs`) +
            FfiConverterOptionalString.allocationSize(value.`memo`) +
            FfiConverterUInt.allocationSize(value.`witnessCount`) +
            FfiConverterBoolean.allocationSize(value.`confirmed`)
    )

    override fun write(value: TxInfo, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`fromAddress`, buf)
            FfiConverterString.write(value.`toAddress`, buf)
            FfiConverterULong.write(value.`amountMuon`, buf)
            FfiConverterULong.write(value.`feeMuon`, buf)
            FfiConverterULong.write(value.`timestampMs`, buf)
            FfiConverterOptionalString.write(value.`memo`, buf)
            FfiConverterUInt.write(value.`witnessCount`, buf)
            FfiConverterBoolean.write(value.`confirmed`, buf)
    }
}



data class WalletBalance (
    var `confirmedMuon`: kotlin.ULong, 
    var `pendingMuon`: kotlin.ULong
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeWalletBalance: FfiConverterRustBuffer<WalletBalance> {
    override fun read(buf: ByteBuffer): WalletBalance {
        return WalletBalance(
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: WalletBalance) = (
            FfiConverterULong.allocationSize(value.`confirmedMuon`) +
            FfiConverterULong.allocationSize(value.`pendingMuon`)
    )

    override fun write(value: WalletBalance, buf: ByteBuffer) {
            FfiConverterULong.write(value.`confirmedMuon`, buf)
            FfiConverterULong.write(value.`pendingMuon`, buf)
    }
}




enum class ConnectivityMode {
    
    INTERNET,
    MESH_ONLY;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeConnectivityMode: FfiConverterRustBuffer<ConnectivityMode> {
    override fun read(buf: ByteBuffer) = try {
        ConnectivityMode.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: ConnectivityMode) = 4UL

    override fun write(value: ConnectivityMode, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class EnergyState {
    
    ACTIVE,
    INTERMITTENT,
    PASSIVE;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeEnergyState: FfiConverterRustBuffer<EnergyState> {
    override fun read(buf: ByteBuffer) = try {
        EnergyState.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: EnergyState) = 4UL

    override fun write(value: EnergyState, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}







public interface NodeEventCallback {
    
    fun `onPeerDiscovered`(`peerId`: kotlin.String)
    
    fun `onPeerLost`(`peerId`: kotlin.String)
    
    fun `onChatReceived`(`message`: ChatMessage)
    
    fun `onMailReceived`(`message`: MailMessage)
    
    fun `onBulletinReceived`(`post`: BulletinPost)
    
    fun `onConnectivityChanged`(`mode`: ConnectivityMode)
    
    companion object
}

// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
internal const val IDX_CALLBACK_FREE = 0
// Callback return codes
internal const val UNIFFI_CALLBACK_SUCCESS = 0
internal const val UNIFFI_CALLBACK_ERROR = 1
internal const val UNIFFI_CALLBACK_UNEXPECTED_ERROR = 2

/**
 * @suppress
 */
public abstract class FfiConverterCallbackInterface<CallbackInterface: Any>: FfiConverter<CallbackInterface, Long> {
    internal val handleMap = UniffiHandleMap<CallbackInterface>()

    internal fun drop(handle: Long) {
        handleMap.remove(handle)
    }

    override fun lift(value: Long): CallbackInterface {
        return handleMap.get(value)
    }

    override fun read(buf: ByteBuffer) = lift(buf.getLong())

    override fun lower(value: CallbackInterface) = handleMap.insert(value)

    override fun allocationSize(value: CallbackInterface) = 8UL

    override fun write(value: CallbackInterface, buf: ByteBuffer) {
        buf.putLong(lower(value))
    }
}

// Put the implementation in an object so we don't pollute the top-level namespace
internal object uniffiCallbackInterfaceNodeEventCallback {
    internal object `onPeerDiscovered`: UniffiCallbackInterfaceNodeEventCallbackMethod0 {
        override fun callback(`uniffiHandle`: Long,`peerId`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,) {
            val uniffiObj = FfiConverterTypeNodeEventCallback.handleMap.get(uniffiHandle)
            val makeCall = { ->
                uniffiObj.`onPeerDiscovered`(
                    FfiConverterString.lift(`peerId`),
                )
            }
            val writeReturn = { _: Unit -> Unit }
            uniffiTraitInterfaceCall(uniffiCallStatus, makeCall, writeReturn)
        }
    }
    internal object `onPeerLost`: UniffiCallbackInterfaceNodeEventCallbackMethod1 {
        override fun callback(`uniffiHandle`: Long,`peerId`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,) {
            val uniffiObj = FfiConverterTypeNodeEventCallback.handleMap.get(uniffiHandle)
            val makeCall = { ->
                uniffiObj.`onPeerLost`(
                    FfiConverterString.lift(`peerId`),
                )
            }
            val writeReturn = { _: Unit -> Unit }
            uniffiTraitInterfaceCall(uniffiCallStatus, makeCall, writeReturn)
        }
    }
    internal object `onChatReceived`: UniffiCallbackInterfaceNodeEventCallbackMethod2 {
        override fun callback(`uniffiHandle`: Long,`message`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,) {
            val uniffiObj = FfiConverterTypeNodeEventCallback.handleMap.get(uniffiHandle)
            val makeCall = { ->
                uniffiObj.`onChatReceived`(
                    FfiConverterTypeChatMessage.lift(`message`),
                )
            }
            val writeReturn = { _: Unit -> Unit }
            uniffiTraitInterfaceCall(uniffiCallStatus, makeCall, writeReturn)
        }
    }
    internal object `onMailReceived`: UniffiCallbackInterfaceNodeEventCallbackMethod3 {
        override fun callback(`uniffiHandle`: Long,`message`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,) {
            val uniffiObj = FfiConverterTypeNodeEventCallback.handleMap.get(uniffiHandle)
            val makeCall = { ->
                uniffiObj.`onMailReceived`(
                    FfiConverterTypeMailMessage.lift(`message`),
                )
            }
            val writeReturn = { _: Unit -> Unit }
            uniffiTraitInterfaceCall(uniffiCallStatus, makeCall, writeReturn)
        }
    }
    internal object `onBulletinReceived`: UniffiCallbackInterfaceNodeEventCallbackMethod4 {
        override fun callback(`uniffiHandle`: Long,`post`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,) {
            val uniffiObj = FfiConverterTypeNodeEventCallback.handleMap.get(uniffiHandle)
            val makeCall = { ->
                uniffiObj.`onBulletinReceived`(
                    FfiConverterTypeBulletinPost.lift(`post`),
                )
            }
            val writeReturn = { _: Unit -> Unit }
            uniffiTraitInterfaceCall(uniffiCallStatus, makeCall, writeReturn)
        }
    }
    internal object `onConnectivityChanged`: UniffiCallbackInterfaceNodeEventCallbackMethod5 {
        override fun callback(`uniffiHandle`: Long,`mode`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,) {
            val uniffiObj = FfiConverterTypeNodeEventCallback.handleMap.get(uniffiHandle)
            val makeCall = { ->
                uniffiObj.`onConnectivityChanged`(
                    FfiConverterTypeConnectivityMode.lift(`mode`),
                )
            }
            val writeReturn = { _: Unit -> Unit }
            uniffiTraitInterfaceCall(uniffiCallStatus, makeCall, writeReturn)
        }
    }

    internal object uniffiFree: UniffiCallbackInterfaceFree {
        override fun callback(handle: Long) {
            FfiConverterTypeNodeEventCallback.handleMap.remove(handle)
        }
    }

    internal var vtable = UniffiVTableCallbackInterfaceNodeEventCallback.UniffiByValue(
        `onPeerDiscovered`,
        `onPeerLost`,
        `onChatReceived`,
        `onMailReceived`,
        `onBulletinReceived`,
        `onConnectivityChanged`,
        uniffiFree,
    )

    // Registers the foreign callback with the Rust side.
    // This method is generated for each callback interface.
    internal fun register(lib: UniffiLib) {
        lib.uniffi_mycelium_ffi_fn_init_callback_vtable_nodeeventcallback(vtable)
    }
}

/**
 * The ffiConverter which transforms the Callbacks in to handles to pass to Rust.
 *
 * @suppress
 */
public object FfiConverterTypeNodeEventCallback: FfiConverterCallbackInterface<NodeEventCallback>()




/**
 * @suppress
 */
public object FfiConverterOptionalULong: FfiConverterRustBuffer<kotlin.ULong?> {
    override fun read(buf: ByteBuffer): kotlin.ULong? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterULong.read(buf)
    }

    override fun allocationSize(value: kotlin.ULong?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterULong.allocationSize(value)
        }
    }

    override fun write(value: kotlin.ULong?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterULong.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypePaymentRequestData: FfiConverterRustBuffer<PaymentRequestData?> {
    override fun read(buf: ByteBuffer): PaymentRequestData? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypePaymentRequestData.read(buf)
    }

    override fun allocationSize(value: PaymentRequestData?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypePaymentRequestData.allocationSize(value)
        }
    }

    override fun write(value: PaymentRequestData?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypePaymentRequestData.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceString: FfiConverterRustBuffer<List<kotlin.String>> {
    override fun read(buf: ByteBuffer): List<kotlin.String> {
        val len = buf.getInt()
        return List<kotlin.String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.String>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterString.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeBulletinPost: FfiConverterRustBuffer<List<BulletinPost>> {
    override fun read(buf: ByteBuffer): List<BulletinPost> {
        val len = buf.getInt()
        return List<BulletinPost>(len) {
            FfiConverterTypeBulletinPost.read(buf)
        }
    }

    override fun allocationSize(value: List<BulletinPost>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeBulletinPost.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<BulletinPost>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeBulletinPost.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeChatMessage: FfiConverterRustBuffer<List<ChatMessage>> {
    override fun read(buf: ByteBuffer): List<ChatMessage> {
        val len = buf.getInt()
        return List<ChatMessage>(len) {
            FfiConverterTypeChatMessage.read(buf)
        }
    }

    override fun allocationSize(value: List<ChatMessage>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeChatMessage.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<ChatMessage>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeChatMessage.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeMailMessage: FfiConverterRustBuffer<List<MailMessage>> {
    override fun read(buf: ByteBuffer): List<MailMessage> {
        val len = buf.getInt()
        return List<MailMessage>(len) {
            FfiConverterTypeMailMessage.read(buf)
        }
    }

    override fun allocationSize(value: List<MailMessage>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeMailMessage.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<MailMessage>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeMailMessage.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeTxInfo: FfiConverterRustBuffer<List<TxInfo>> {
    override fun read(buf: ByteBuffer): List<TxInfo> {
        val len = buf.getInt()
        return List<TxInfo>(len) {
            FfiConverterTypeTxInfo.read(buf)
        }
    }

    override fun allocationSize(value: List<TxInfo>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeTxInfo.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<TxInfo>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeTxInfo.write(it, buf)
        }
    }
} fun `addBootstrapPeer`(`multiaddr`: kotlin.String)
        = 
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_add_bootstrap_peer(
        FfiConverterString.lower(`multiaddr`),_status)
}
    
    
 fun `buildPaymentRequestUri`(`toAddress`: kotlin.String, `amountMuon`: kotlin.ULong, `memo`: kotlin.String?): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_build_payment_request_uri(
        FfiConverterString.lower(`toAddress`),FfiConverterULong.lower(`amountMuon`),FfiConverterOptionalString.lower(`memo`),_status)
}
    )
    }
    
 fun `bulletinsForScope`(`scope`: kotlin.String): List<BulletinPost> {
            return FfiConverterSequenceTypeBulletinPost.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_bulletins_for_scope(
        FfiConverterString.lower(`scope`),_status)
}
    )
    }
    
 fun `chatHistory`(`peerId`: kotlin.String, `limit`: kotlin.UInt): List<ChatMessage> {
            return FfiConverterSequenceTypeChatMessage.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_chat_history(
        FfiConverterString.lower(`peerId`),FfiConverterUInt.lower(`limit`),_status)
}
    )
    }
    
 fun `currentConnectivityMode`(): ConnectivityMode {
            return FfiConverterTypeConnectivityMode.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_current_connectivity_mode(
        _status)
}
    )
    }
    
 fun `displayName`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_display_name(
        _status)
}
    )
    }
    
 fun `getHotWalletConfig`(): HotWalletConfig {
            return FfiConverterTypeHotWalletConfig.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_get_hot_wallet_config(
        _status)
}
    )
    }
    
 fun `hotWalletStatus`(): HotWalletStatus {
            return FfiConverterTypeHotWalletStatus.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_hot_wallet_status(
        _status)
}
    )
    }
    
 fun `initNode`(`config`: NodeConfig)
        = 
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_init_node(
        FfiConverterTypeNodeConfig.lower(`config`),_status)
}
    
    
 fun `knownPeers`(): List<kotlin.String> {
            return FfiConverterSequenceString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_known_peers(
        _status)
}
    )
    }
    
 fun `localPeerId`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_local_peer_id(
        _status)
}
    )
    }
    
 fun `mailInbox`(`limit`: kotlin.UInt): List<MailMessage> {
            return FfiConverterSequenceTypeMailMessage.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_mail_inbox(
        FfiConverterUInt.lower(`limit`),_status)
}
    )
    }
    
 fun `mailSent`(`limit`: kotlin.UInt): List<MailMessage> {
            return FfiConverterSequenceTypeMailMessage.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_mail_sent(
        FfiConverterUInt.lower(`limit`),_status)
}
    )
    }
    
 fun `markMailRead`(`mailId`: kotlin.String)
        = 
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_mark_mail_read(
        FfiConverterString.lower(`mailId`),_status)
}
    
    
 fun `metrics`(): NodeMetrics {
            return FfiConverterTypeNodeMetrics.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_metrics(
        _status)
}
    )
    }
    
 fun `parsePaymentRequestUri`(`uri`: kotlin.String): PaymentRequestData? {
            return FfiConverterOptionalTypePaymentRequestData.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_parse_payment_request_uri(
        FfiConverterString.lower(`uri`),_status)
}
    )
    }
    
 fun `postBulletin`(`scope`: kotlin.String, `title`: kotlin.String, `body`: kotlin.String, `ttlSecs`: kotlin.ULong)
        = 
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_post_bulletin(
        FfiConverterString.lower(`scope`),FfiConverterString.lower(`title`),FfiConverterString.lower(`body`),FfiConverterULong.lower(`ttlSecs`),_status)
}
    
    
 fun `requestFaucet`()
        = 
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_request_faucet(
        _status)
}
    
    
 fun `sendChatBroadcast`(`body`: kotlin.String)
        = 
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_send_chat_broadcast(
        FfiConverterString.lower(`body`),_status)
}
    
    
 fun `sendChatDirect`(`toPeer`: kotlin.String, `body`: kotlin.String)
        = 
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_send_chat_direct(
        FfiConverterString.lower(`toPeer`),FfiConverterString.lower(`body`),_status)
}
    
    
 fun `sendMail`(`toPeer`: kotlin.String, `subject`: kotlin.String, `body`: kotlin.String)
        = 
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_send_mail(
        FfiConverterString.lower(`toPeer`),FfiConverterString.lower(`subject`),FfiConverterString.lower(`body`),_status)
}
    
    
 fun `sendTransaction`(`toAddress`: kotlin.String, `amountMuon`: kotlin.ULong, `memo`: kotlin.String?)
        = 
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_send_transaction(
        FfiConverterString.lower(`toAddress`),FfiConverterULong.lower(`amountMuon`),FfiConverterOptionalString.lower(`memo`),_status)
}
    
    
 fun `setColdWalletAddress`(`address`: kotlin.String?)
        = 
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_set_cold_wallet_address(
        FfiConverterOptionalString.lower(`address`),_status)
}
    
    
 fun `setDisplayName`(`name`: kotlin.String)
        = 
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_set_display_name(
        FfiConverterString.lower(`name`),_status)
}
    
    
 fun `setEnergyState`(`state`: EnergyState)
        = 
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_set_energy_state(
        FfiConverterTypeEnergyState.lower(`state`),_status)
}
    
    
 fun `setEventCallback`(`callback`: NodeEventCallback)
        = 
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_set_event_callback(
        FfiConverterTypeNodeEventCallback.lower(`callback`),_status)
}
    
    
 fun `setHotWalletConfig`(`config`: HotWalletConfig)
        = 
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_set_hot_wallet_config(
        FfiConverterTypeHotWalletConfig.lower(`config`),_status)
}
    
    
 fun `stopNode`()
        = 
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_stop_node(
        _status)
}
    
    
 fun `walletAddress`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_wallet_address(
        _status)
}
    )
    }
    
 fun `walletBalance`(): WalletBalance {
            return FfiConverterTypeWalletBalance.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_wallet_balance(
        _status)
}
    )
    }
    
 fun `walletRecentTransactions`(`limit`: kotlin.UInt): List<TxInfo> {
            return FfiConverterSequenceTypeTxInfo.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_mycelium_ffi_fn_func_wallet_recent_transactions(
        FfiConverterUInt.lower(`limit`),_status)
}
    )
    }
    


